version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-indentity
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3326:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
